import { boolean, date, integer, jsonb, numeric, pgTable, serial, text, timestamp, unique } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const rentals = pgTable('rentals', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), contractNo: text('contractNo').notNull(), customerCompany: text('customer_company'), customerName: text('customerName').notNull(), customerPhone: text('customerPhone').notNull(), customerAddress: text('customerAddress'), deviceName: text('deviceName').notNull(), deviceType: text('deviceType').notNull().default('台式机'), deviceConfig: text('deviceConfig'), deviceCode: text('deviceCode'), cpu: text('cpu'), motherboard: text('motherboard'), memory: text('memory'), storage: text('storage'), graphicsCard: text('graphicsCard'), powerSupply: text('powerSupply'), caseModel: text('caseModel'), monitorInfo: text('monitorInfo'), screenSize: text('screenSize'), screenResolution: text('screenResolution'), refreshRate: text('refreshRate'), panelType: text('panelType'), ports: text('ports'), batteryInfo: text('batteryInfo'), adapterInfo: text('adapterInfo'), accessories: text('accessories'), colorGamut: text('colorGamut'), quantity: integer('quantity').notNull().default(1), startDate: date('startDate').notNull(), endDate: date('endDate').notNull(), monthlyRent: numeric('monthlyRent', { precision: 12, scale: 2 }).notNull().default('0'), totalRent: numeric('totalRent', { precision: 12, scale: 2 }).notNull().default('0'), deposit: numeric('deposit', { precision: 12, scale: 2 }).notNull().default('0'), paidAmount: numeric('paidAmount', { precision: 12, scale: 2 }).notNull().default('0'), paymentStatus: text('paymentStatus').notNull().default('待收款'), status: text('status').notNull().default('在租'), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (table) => [unique().on(table.userId, table.contractNo)])

export const rentalItems = pgTable('rental_items', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(),
  deviceName: text('deviceName').notNull(), deviceType: text('deviceType').notNull().default('台式机'), deviceCode: text('deviceCode'), deviceConfig: text('deviceConfig'),
  quantity: integer('quantity').notNull().default(1), startDate: date('startDate'), endDate: date('endDate'), monthlyRent: numeric('monthlyRent', { precision: 12, scale: 2 }).notNull().default('0'), totalRent: numeric('totalRent', { precision: 12, scale: 2 }).notNull().default('0'), boughtOutQuantity: integer('boughtOutQuantity').notNull().default(0), returnedQuantity: integer('returnedQuantity').notNull().default(0), lostQuantity: integer('lostQuantity').notNull().default(0), buyoutAmount: numeric('buyoutAmount', { precision: 12, scale: 2 }).notNull().default('0'),
  cpu: text('cpu'), motherboard: text('motherboard'), memory: text('memory'), storage: text('storage'), graphicsCard: text('graphicsCard'), powerSupply: text('powerSupply'), caseModel: text('caseModel'), monitorInfo: text('monitorInfo'), screenSize: text('screenSize'), screenResolution: text('screenResolution'), refreshRate: text('refreshRate'), panelType: text('panelType'), ports: text('ports'), batteryInfo: text('batteryInfo'), adapterInfo: text('adapterInfo'), accessories: text('accessories'), colorGamut: text('colorGamut'),
  createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})

export const buyoutRecords = pgTable('buyout_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), rentalItemId: integer('rentalItemId').notNull(), quantity: integer('quantity').notNull(), unitPrice: numeric('unitPrice', { precision: 12, scale: 2 }).notNull(), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), buyoutDate: date('buyoutDate').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const renewalRecords = pgTable('renewal_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), sourceRentalItemId: integer('sourceRentalItemId').notNull(), renewedRentalItemId: integer('renewedRentalItemId').notNull(), quantity: integer('quantity').notNull(), renewalMonths: integer('renewalMonths'), billingUnit: text('billingUnit'), duration: integer('duration'), unitPrice: numeric('unitPrice', { precision: 12, scale: 2 }), oldMonthlyRent: numeric('oldMonthlyRent', { precision: 12, scale: 2 }).notNull(), newMonthlyRent: numeric('newMonthlyRent', { precision: 12, scale: 2 }).notNull(), oldEndDate: date('oldEndDate').notNull(), newEndDate: date('newEndDate').notNull(), renewalAmount: numeric('renewalAmount', { precision: 12, scale: 2 }).notNull().default('0'), renewalDate: date('renewalDate').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const paymentRecords = pgTable('payment_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), renewalRecordId: integer('renewalRecordId'), buyoutRecordId: integer('buyoutRecordId'), returnRecordId: integer('returnRecordId'), lossRecordId: integer('lossRecordId'), operatorName: text('operatorName'), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), paymentDate: date('paymentDate').notNull(), paymentMethod: text('paymentMethod').notNull(), feeType: text('feeType').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const receivableBills = pgTable('receivable_bills', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), billNo: text('billNo').notNull(), periodStart: date('periodStart').notNull(), periodEnd: date('periodEnd').notNull(), dueDate: date('dueDate').notNull(), billType: text('billType').notNull().default('租金'), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), paidAmount: numeric('paidAmount', { precision: 12, scale: 2 }).notNull().default('0'), status: text('status').notNull().default('待收'), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
}, (table) => [unique().on(table.userId, table.billNo)])

export const paymentAllocations = pgTable('payment_allocations', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), paymentRecordId: integer('paymentRecordId').notNull(), billId: integer('billId').notNull(), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const accountLedger = pgTable('account_ledger', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), entryType: text('entryType').notNull(), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), entryDate: date('entryDate').notNull(), paymentRecordId: integer('paymentRecordId'), relatedEntryId: integer('relatedEntryId'), operatorName: text('operatorName').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const rentalEvents = pgTable('rental_events', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), eventType: text('eventType').notNull(), status: text('status').notNull().default('已完成'), eventDate: date('eventDate').notNull(), itemId: integer('itemId'), beforeSnapshot: jsonb('beforeSnapshot'), afterSnapshot: jsonb('afterSnapshot'), reason: text('reason'), feeAdjustment: numeric('feeAdjustment', { precision: 12, scale: 2 }).notNull().default('0'), repairCost: numeric('repairCost', { precision: 12, scale: 2 }).notNull().default('0'), customerCharge: numeric('customerCharge', { precision: 12, scale: 2 }).notNull().default('0'), faultDescription: text('faultDescription'), resolution: text('resolution'), completedDate: date('completedDate'), operatorName: text('operatorName').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const returnRecords = pgTable('return_records', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), rentalItemId: integer('rentalItemId').notNull(), quantity: integer('quantity').notNull(), returnDate: date('returnDate').notNull(), condition: text('condition').notNull(), deductionAmount: numeric('deductionAmount', { precision: 12, scale: 2 }).notNull().default('0'), depositRefund: numeric('depositRefund', { precision: 12, scale: 2 }).notNull().default('0'), notes: text('notes'), operatorName: text('operatorName').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const lossRecords = pgTable('loss_records', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull(), rentalItemId: integer('rentalItemId').notNull(), quantity: integer('quantity').notNull(), lossDate: date('lossDate').notNull(), unitCompensation: numeric('unitCompensation', { precision: 12, scale: 2 }).notNull(), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), notes: text('notes'), operatorName: text('operatorName').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const businessSettings = pgTable('business_settings', { id: serial('id').primaryKey(), userId: text('userId').notNull().unique(), storeName: text('storeName'), lessorType: text('lessorType').notNull().default('企业'), lessorName: text('lessorName').notNull().default(''), identityNo: text('identityNo'), contactName: text('contactName'), phone: text('phone'), address: text('address'), paymentInfo: text('paymentInfo'), contractTerms: text('contractTerms'), themeMode: text('themeMode').notNull().default('system'), themeColor: text('themeColor').notNull().default('green'), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const contractSnapshots = pgTable('contract_snapshots', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: integer('rentalId').notNull().unique(), customerType: text('customerType').notNull().default('个人'), customerIdentityNo: text('customerIdentityNo'), customerCompany: text('customerCompany'), customerCreditCode: text('customerCreditCode'), lessorJson: text('lessorJson').notNull(), customerJson: text('customerJson').notNull(), itemsJson: text('itemsJson').notNull(), terms: text('terms').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const organizationMembers = pgTable('organization_members', { id: serial('id').primaryKey(), ownerId: text('ownerId').notNull(), memberUserId: text('memberUserId').notNull().unique(), role: text('role').notNull().default('employee'), active: boolean('active').notNull().default(true), permissions: text('permissions').notNull().default('rentals'), updatedAt: timestamp('updatedAt').notNull().defaultNow() })

export const customerPortals = pgTable('customer_portals', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), phone: text('phone').notNull(), customerName: text('customerName').notNull(), accessTokenHash: text('accessTokenHash').notNull().unique(), passwordHash: text('passwordHash').notNull(), status: text('status').notNull().default('active'), failedAttempts: integer('failedAttempts').notNull().default(0), lockedUntil: timestamp('lockedUntil'), sessionVersion: integer('sessionVersion').notNull().default(1), lastLoginAt: timestamp('lastLoginAt'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
}, (table) => [unique().on(table.userId, table.phone)])

export type Rental = typeof rentals.$inferSelect
export type RentalItem = typeof rentalItems.$inferSelect
export type BuyoutRecord = typeof buyoutRecords.$inferSelect
export type RenewalRecord = typeof renewalRecords.$inferSelect
export type PaymentRecord = typeof paymentRecords.$inferSelect
export type RentalEvent = typeof rentalEvents.$inferSelect
export type ReceivableBill = typeof receivableBills.$inferSelect
export type PaymentAllocation = typeof paymentAllocations.$inferSelect
export type AccountLedgerEntry = typeof accountLedger.$inferSelect
