// @ts-expect-error generated by OpenNext during build
import handler from './.open-next/worker.js'

interface WorkerEnv extends CloudflareEnv {
  CRON_SECRET?: string
}

export default {
  fetch: handler.fetch,
  async scheduled(_event: ScheduledController, env: WorkerEnv, ctx: ExecutionContext) {
    if (!env.CRON_SECRET) {
      console.error('[cron] CRON_SECRET 未配置，已跳过到期提醒')
      return
    }
    ctx.waitUntil((async () => {
      const response = await handler.fetch(new Request('https://www.tuzhuzu.cn/api/cron/due-reminders', { method: 'POST', headers: { authorization: `Bearer ${env.CRON_SECRET}` } }), env, ctx)
      if (!response.ok) throw new Error(`到期提醒任务失败：HTTP ${response.status}`)
      console.info('[cron] 到期提醒任务完成', await response.json())
    })())
  },
} satisfies ExportedHandler<WorkerEnv>

// @ts-expect-error generated by OpenNext during build
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'
