'use server'

import { headers } from 'next/headers'
import { revalidatePath } from 'next/cache'
import { and, asc, desc, eq, gte, lte } from 'drizzle-orm'
import { z } from 'zod'
import { getAccessContext, type ModulePermission } from '@/lib/access'
import { db } from '@/lib/db'
import { businessSettings, contractSnapshots, organizationMembers, paymentRecords, rentalItems, rentals, user } from '@/lib/db/schema'

const DEFAULT_TERMS = `1. 交付与验收：承租方签收设备时应核对数量、配置及外观，签收即视为验收合格。\n2. 租金与押金：承租方按约定时间支付租金及押金；押金不得直接抵扣租金。\n3. 使用与保管：承租方应合理使用设备，不得擅自拆机、转租或用于违法活动。\n4. 维修责任：正常使用产生的故障由出租方负责；人为损坏产生的费用由承租方承担。\n5. 丢失与损坏：设备丢失或无法修复时，承租方按双方确认价值承担赔偿。\n6. 续租与退租：续租须在到期前确认；退租以设备实际归还并验收之日为准。\n7. 违约与争议：违约方承担相应损失；争议应先协商，协商不成由出租方所在地有管辖权的人民法院处理。\n8. 通知送达：本合同记载的电话和地址为有效联系方式，变更应及时书面通知。`

async function userId(permission?:ModulePermission) { return (await getAccessContext(permission)).userId }
async function requireAdmin() { const context=await getAccessContext('账号管理');if(context.role!=='admin')throw new Error('仅管理员可管理员工账号');return context.userId }

export async function getFinanceData(from?:string,to?:string){const id=await userId('资金查看');const filters=[eq(paymentRecords.userId,id)];if(from)filters.push(gte(paymentRecords.paymentDate,from));if(to)filters.push(lte(paymentRecords.paymentDate,to));const rows=await db.select({id:paymentRecords.id,rentalId:paymentRecords.rentalId,amount:paymentRecords.amount,paymentDate:paymentRecords.paymentDate,paymentMethod:paymentRecords.paymentMethod,feeType:paymentRecords.feeType,notes:paymentRecords.notes,operatorName:paymentRecords.operatorName,contractNo:rentals.contractNo,customerCompany:rentals.customerCompany,customerName:rentals.customerName,customerPhone:rentals.customerPhone,deviceName:rentals.deviceName,renewalRecordId:paymentRecords.renewalRecordId}).from(paymentRecords).innerJoin(rentals,and(eq(rentals.id,paymentRecords.rentalId),eq(rentals.userId,id))).where(and(...filters)).orderBy(desc(paymentRecords.paymentDate),desc(paymentRecords.id));const now=new Date();const day=now.toISOString().slice(0,10);const month=day.slice(0,7);const year=day.slice(0,4);const all=await db.select({date:paymentRecords.paymentDate,amount:paymentRecords.amount,feeType:paymentRecords.feeType}).from(paymentRecords).where(eq(paymentRecords.userId,id));const sum=(test:(d:string)=>boolean)=>all.filter(x=>test(x.date)).reduce((s,x)=>s+Number(x.amount),0);return{rows,summary:{today:sum(d=>d===day),month:sum(d=>d.startsWith(month)),year:sum(d=>d.startsWith(year)),all:sum(()=>true)},types:Object.entries(all.reduce<Record<string,number>>((a,x)=>(a[x.feeType]=(a[x.feeType]||0)+Number(x.amount),a),{}))}}

async function loadSettings(id:string){const [row]=await db.select().from(businessSettings).where(eq(businessSettings.userId,id));return row??{userId:id,storeName:'速维租赁管理',lessorType:'企业',lessorName:'',identityNo:'',contactName:'',phone:'',address:'',paymentInfo:'',contractTerms:DEFAULT_TERMS,themeMode:'system',themeColor:'green'}}
export async function getSettings(){const id=await userId('系统设置');return loadSettings(id)}
export async function getStoreName(){const id=await userId();const settings=await loadSettings(id);return settings.storeName?.trim()||'速维租赁管理'}
const settingsSchema=z.object({storeName:z.string().trim().min(2,'店铺名称至少需要 2 个字').max(40,'店铺名称最多 40 个字'),lessorType:z.enum(['个人','企业']),lessorName:z.string().min(2),identityNo:z.string().optional(),contactName:z.string().optional(),phone:z.string().optional(),address:z.string().optional(),paymentInfo:z.string().optional(),contractTerms:z.string().min(20),themeMode:z.enum(['light','dark','system']),themeColor:z.enum(['green','blue','orange'])})
export async function saveSettings(input:z.infer<typeof settingsSchema>){const id=await userId('系统设置');const v=settingsSchema.parse(input);await db.insert(businessSettings).values({...v,userId:id}).onConflictDoUpdate({target:businessSettings.userId,set:{...v,updatedAt:new Date()}});revalidatePath('/');revalidatePath('/settings')}

export async function getContract(rentalId:number){const id=await userId('合同管理');const [rental]=await db.select().from(rentals).where(and(eq(rentals.userId,id),eq(rentals.id,rentalId)));if(!rental)throw new Error('合同不存在');const items=await db.select().from(rentalItems).where(and(eq(rentalItems.userId,id),eq(rentalItems.rentalId,rentalId))).orderBy(asc(rentalItems.id));const [snapshot]=await db.select().from(contractSnapshots).where(and(eq(contractSnapshots.userId,id),eq(contractSnapshots.rentalId,rentalId)));const settings=await loadSettings(id);return{rental,items,settings,snapshot}}
export async function saveContractSnapshot(rentalId:number,input:{customerType:'个人'|'企业';customerIdentityNo?:string;customerCompany?:string;customerCreditCode?:string;terms:string}){const id=await userId('合同管理');const [rental]=await db.select().from(rentals).where(and(eq(rentals.userId,id),eq(rentals.id,rentalId)));if(!rental)throw new Error('合同不存在');const items=await db.select().from(rentalItems).where(and(eq(rentalItems.userId,id),eq(rentalItems.rentalId,rentalId)));const settings=await loadSettings(id);const values={userId:id,rentalId,customerType:input.customerType,customerIdentityNo:input.customerIdentityNo,customerCompany:input.customerCompany,customerCreditCode:input.customerCreditCode,lessorJson:JSON.stringify(settings),customerJson:JSON.stringify({name:rental.customerName,phone:rental.customerPhone,address:rental.customerAddress}),itemsJson:JSON.stringify(items),terms:input.terms};await db.insert(contractSnapshots).values(values).onConflictDoUpdate({target:contractSnapshots.rentalId,set:{...values,updatedAt:new Date()}});revalidatePath(`/contracts/${rentalId}`)}

export async function getAccounts(){const id=await requireAdmin();const owner=await db.select({id:user.id,name:user.name,email:user.email,createdAt:user.createdAt}).from(user).where(eq(user.id,id));const members=await db.select({id:user.id,name:user.name,email:user.email,role:organizationMembers.role,active:organizationMembers.active,permissions:organizationMembers.permissions,updatedAt:organizationMembers.updatedAt}).from(organizationMembers).innerJoin(user,eq(user.id,organizationMembers.memberUserId)).where(eq(organizationMembers.ownerId,id));return{owner,members}}
export async function addMember(email:string,permissions:string[]){const id=await requireAdmin();const normalized=z.string().email().parse(email.trim().toLowerCase());const [member]=await db.select().from(user).where(eq(user.email,normalized));if(!member)throw new Error('该邮箱尚未注册，请员工先创建登录账号');if(member.id===id)throw new Error('不能添加自己为员工');await db.insert(organizationMembers).values({ownerId:id,memberUserId:member.id,permissions:permissions.join(',')}).onConflictDoUpdate({target:organizationMembers.memberUserId,set:{ownerId:id,permissions:permissions.join(','),active:true,updatedAt:new Date()}});revalidatePath('/accounts')}
export async function updateMember(memberUserId:string,input:{active:boolean;permissions:string[]}){const id=await requireAdmin();await db.update(organizationMembers).set({active:input.active,permissions:input.permissions.join(','),updatedAt:new Date()}).where(and(eq(organizationMembers.ownerId,id),eq(organizationMembers.memberUserId,memberUserId)));revalidatePath('/accounts')}
