import Link from 'next/link'
import { ArrowLeft, Banknote, Search } from 'lucide-react'

type Row = { id:number; rentalId:number; renewalRecordId:number|null; amount:string; paymentDate:string; paymentMethod:string; feeType:string; notes:string|null; operatorName:string|null; contractNo:string; customerCompany:string|null; customerName:string; customerPhone:string; deviceName:string }
type Data = { rows:Row[]; summary:{today:number;month:number;year:number;all:number}; types:Array<[string,number]>; total:number; page:number; pageCount:number }
type Filters = { query:string; type:string; method:string; from:string; to:string }
const money = (value:number|string) => new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(Number(value))

export function FinanceLedger({ data, filters }: { data:Data; filters:Filters }) {
  return <main className="min-h-svh bg-background p-4 pb-24 md:p-6 md:pb-24"><div className="mx-auto flex max-w-[1400px] flex-col gap-6"><Link href="/dashboard" className="inline-flex items-center gap-2 self-start text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>返回经营总览</Link><header className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Banknote/></span><div><h1 className="text-2xl font-bold text-balance">资金流水</h1><p className="text-sm text-muted-foreground">数据库聚合统计与服务端分页，适合长期积累的大量收款记录</p></div></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['今天',data.summary.today],['本月',data.summary.month],['今年',data.summary.year],['全部',data.summary.all]].map(([label,value]) => <div key={String(label)} className="rounded-xl border bg-card p-4"><p className="text-sm text-muted-foreground">{label}实收</p><p className="mt-2 text-xl font-bold md:text-2xl">{money(value)}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border bg-card"><div className="flex flex-col gap-4 border-b p-4"><div><h2 className="font-semibold">收款明细</h2><p className="text-sm text-muted-foreground">共 {data.total.toLocaleString('zh-CN')} 笔，当前第 {data.page}/{data.pageCount} 页</p></div><form action="/finance" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><label className="flex h-10 items-center gap-2 rounded-lg border px-3 sm:col-span-2"><Search className="size-4 text-muted-foreground"/><input name="query" aria-label="搜索资金流水" defaultValue={filters.query} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="公司、联系人、合同、设备"/></label><select name="type" aria-label="款项类型" defaultValue={filters.type} className="h-10 rounded-lg border bg-background px-3"><option>全部</option>{data.types.map(([value]) => <option key={value}>{value}</option>)}</select><select name="method" aria-label="支付方式" defaultValue={filters.method} className="h-10 rounded-lg border bg-background px-3">{['全部','现金','微信','支付宝','银行转账','其他'].map((value) => <option key={value}>{value}</option>)}</select><input name="from" aria-label="开始日期" type="date" defaultValue={filters.from} className="h-10 rounded-lg border bg-background px-3"/><input name="to" aria-label="结束日期" type="date" defaultValue={filters.to} className="h-10 rounded-lg border bg-background px-3"/><div className="flex gap-2 lg:col-span-6"><button className="primary-button" type="submit">查询</button><Link href="/finance" className="secondary-button">清除条件</Link></div></form></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3">日期</th><th className="p-3">金额</th><th className="p-3">客户</th><th className="p-3">合同</th><th className="p-3">方式 / 类型</th><th className="p-3">备注 / 经办</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t hover:bg-muted/40"><td className="p-3">{row.paymentDate}</td><td className="p-3 font-bold">{money(row.amount)}</td><td className="p-3"><p>{row.customerCompany||row.customerName}</p><p className="text-xs text-muted-foreground">{row.customerName} · {row.customerPhone}</p></td><td className="p-3"><Link className="font-medium text-primary" href={`/dashboard?rental=${row.rentalId}`}>{row.contractNo}</Link><p className="text-xs text-muted-foreground">{row.deviceName}</p></td><td className="p-3">{row.paymentMethod}<p className="text-xs text-muted-foreground">{row.feeType}</p></td><td className="p-3">{row.notes||'无备注'}<p className="text-xs text-muted-foreground">{row.operatorName||'历史记录'}</p></td></tr>)}</tbody></table></div>
      <div className="flex flex-col gap-3 p-3 md:hidden">{data.rows.map((row) => <article key={row.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{row.paymentDate} · {row.paymentMethod}</p><p className="mt-1 text-xl font-bold">{money(row.amount)}</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">{row.feeType}</span></div><div className="mt-4 flex flex-col gap-3 text-sm"><p><span className="text-muted-foreground">客户：</span>{row.customerCompany||row.customerName}</p><p><span className="text-muted-foreground">合同：</span><Link className="font-medium text-primary" href={`/dashboard?rental=${row.rentalId}`}>{row.contractNo}</Link></p><p><span className="text-muted-foreground">经办：</span>{row.operatorName||'历史记录'}</p></div></article>)}</div>
      {!data.rows.length && <p className="py-10 text-center text-sm text-muted-foreground">没有符合条件的收款记录</p>}
    </section>
  </div></main>
}
