'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BadgeCheck, Check, Clock3, Headphones, Monitor, Phone, QrCode, ShieldCheck, Truck } from 'lucide-react'

type Package = { id: number; name: string; subtitle: string; monthlyPrice: number; cpuSpec: string; memorySpec: string; storageSpec: string; graphicsSpec: string; displaySpec: string; audience: string; badge: string }

export function MarketingHome({ packages, qrCode }: { packages: Package[]; qrCode: string }) {
  return <main className="min-h-svh bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-6"><Link href="/" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Monitor className="size-5" /></span><div><p className="font-bold leading-none">速维电脑租赁</p><p className="mt-1 text-xs text-muted-foreground">电脑设备租赁 · 灵活配置</p></div></Link><nav aria-label="官网导航" className="hidden items-center gap-6 text-sm font-medium md:flex"><a href="#packages">租赁方案</a><a href="#service">服务保障</a><a href="#customer">客户服务</a></nav><div className="flex items-center gap-2"><a href="tel:05972685521" className="hidden h-9 items-center gap-2 rounded-lg border px-3 text-sm font-semibold sm:flex"><Phone className="size-4" />0597-2685521</a><Link href="/dashboard" className="h-9 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">员工登录</Link></div></div></header>

    <section className="border-b bg-card"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 md:px-6 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div className="flex flex-col items-start justify-center"><span className="rounded-full border bg-background px-3 py-1 text-sm font-medium text-primary">台式机为主 · 多类设备可选</span><h1 className="mt-6 max-w-3xl text-balance text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">服务电商、公司、个人与游戏工作室<br /><span className="text-primary">灵活租用合适的电脑设备</span></h1><p className="mt-6 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">以台式电脑租赁为核心，同时提供笔记本、显示器和一体机。支持单台租用与批量部署，根据使用场景、性能需求和租期匹配设备方案。</p><div className="mt-8 flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><a href="tel:05972685521" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 font-semibold text-primary-foreground"><Phone className="size-5" />电话咨询租机</a><Link href="/customer-login" className="flex h-12 items-center justify-center gap-2 rounded-xl border bg-background px-6 font-semibold">查看我的租赁<ArrowRight className="size-5" /></Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground">{['配置匹配','租期灵活','持续服务'].map((text) => <span key={text} className="flex items-center gap-2"><Check className="size-4 text-primary" />{text}</span>)}</div></div><div className="relative overflow-hidden rounded-3xl border bg-background shadow-xl"><Image src="/images/website/hero-chinese-team.png" alt="中国电商与公司团队使用多台台式电脑办公" width={1800} height={1200} priority sizes="(min-width: 1024px) 44vw, 100vw" className="aspect-[4/3] h-full min-h-96 w-full object-cover" /><div className="absolute inset-x-4 bottom-4 rounded-2xl border border-primary-foreground/20 bg-primary/95 p-4 text-primary-foreground shadow-lg sm:inset-x-6 sm:bottom-6 sm:p-5"><div className="flex items-end justify-between gap-4"><div><p className="text-sm opacity-80">台式机为主 · 多类设备可选</p><p className="mt-1 text-xl font-bold">选配、交付、维护全程支持</p></div><a href="tel:05972685521" className="hidden shrink-0 rounded-lg bg-primary-foreground px-4 py-2 text-sm font-bold text-primary sm:block">电话问方案</a></div><div className="mt-4 grid grid-cols-3 gap-2 border-t border-primary-foreground/20 pt-4 text-center text-xs"><span className="flex items-center justify-center gap-1"><Truck className="size-4" />本地交付</span><span className="flex items-center justify-center gap-1"><ShieldCheck className="size-4" />租期保障</span><span className="flex items-center justify-center gap-1"><Headphones className="size-4" />售后响应</span></div></div></div></div></section>

    <section aria-labelledby="device-types" className="border-b bg-background"><div className="mx-auto max-w-7xl px-4 py-14 md:px-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold text-primary">设备类型</p><h2 id="device-types" className="mt-2 text-balance text-3xl font-bold">台式机是核心，其他设备按需组合</h2></div><p className="max-w-xl text-sm leading-6 text-muted-foreground">针对长期多任务、批量工位和高性能需求优先推荐台式机；移动办公、前台展示及扩展屏幕可搭配其他设备。</p></div><div className="mt-8 grid gap-4 lg:grid-cols-[2fr_1fr_1fr_1fr]"><article className="rounded-2xl border bg-primary p-6 text-primary-foreground"><p className="text-sm font-semibold opacity-80">核心租赁设备</p><h3 className="mt-3 text-2xl font-bold">台式电脑</h3><p className="mt-3 text-sm leading-6 opacity-85">覆盖约八成常见需求，适合电商运营、公司工位、游戏工作室和高性能个人用机。</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-medium"><span className="rounded-full bg-primary-foreground/15 px-3 py-1.5">配置选择丰富</span><span className="rounded-full bg-primary-foreground/15 px-3 py-1.5">适合批量部署</span><span className="rounded-full bg-primary-foreground/15 px-3 py-1.5">升级维护方便</span></div></article>{[{name:'笔记本电脑',desc:'移动办公、出差与临时会议'},{name:'显示器',desc:'双屏办公、设计和高刷需求'},{name:'一体机',desc:'前台、门店和简洁办公空间'}].map((device)=><article key={device.name} className="rounded-2xl border bg-card p-5"><span className="flex size-10 items-center justify-center rounded-xl bg-muted text-primary"><Monitor className="size-5" /></span><h3 className="mt-5 font-bold">{device.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{device.desc}</p></article>)}</div></div></section>

    <section id="packages" className="mx-auto max-w-7xl px-4 py-16 md:px-6 lg:py-24"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">电脑设备租赁方案</p><h2 className="mt-3 text-balance text-3xl font-bold sm:text-4xl">台式机为主，按实际需求配置</h2><p className="mt-4 leading-relaxed text-muted-foreground">约 80% 的租赁需求为台式电脑，同时可提供笔记本、显示器和一体机。最终配置与费用将结合用途、数量、租期和交付地区确认。</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{packages.map((item) => <article key={item.id} className="flex flex-col rounded-2xl border bg-card p-5 transition-transform hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-primary">{item.badge}</p><h3 className="mt-2 text-xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.subtitle}</p></div><Monitor className="size-6 shrink-0 text-primary" /></div><p className="mt-6"><span className="text-sm text-muted-foreground">¥</span><span className="text-4xl font-bold">{item.monthlyPrice}</span><span className="text-sm text-muted-foreground"> / 月起</span></p><ul className="mt-6 flex flex-1 flex-col gap-3 text-sm">{[item.cpuSpec, item.memorySpec, item.storageSpec, item.graphicsSpec, item.displaySpec].filter(Boolean).map((spec) => <li key={spec} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{spec}</li>)}</ul><p className="mt-5 rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">适合：{item.audience}</p><a href="tel:05972685521" className="mt-4 flex h-10 items-center justify-center rounded-lg border font-semibold hover:bg-muted">咨询这套配置</a></article>)}</div></section>

    <section className="border-t bg-card"><div className="mx-auto max-w-7xl px-4 py-16 md:px-6 lg:py-24"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">适用客户与场景</p><h2 className="mt-3 text-balance text-3xl font-bold sm:text-4xl">从个人单台使用到公司批量部署</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">覆盖电商运营、企业办公、个人临时用机和游戏工作室，可搭配显示器及相关配件。</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{[{src:'/images/website/ecommerce-team.png',alt:'中国电商运营人员使用双屏台式电脑处理店铺业务',title:'电商运营',text:'适合店群运营、客服与多任务处理，可按软件数量和账号规模匹配台式机配置。'},{src:'/images/website/company-office.png',alt:'中国公司员工在多工位办公室使用电脑',title:'公司办公',text:'支持新团队组建、临时项目和人员扩充，提供台式机、显示器及批量部署。'},{src:'/images/website/personal-user.png',alt:'中国个人用户在居家工作区使用电脑',title:'个人用机',text:'适合短期办公、学习、创作和娱乐，可灵活选择台式机、笔记本或一体机。'},{src:'/images/website/gaming-studio.png',alt:'中国游戏工作室成员使用高性能台式电脑',title:'游戏工作室',text:'面向开发、测试与高性能应用，提供高配置台式机和高刷新率显示器组合。'}].map((scene)=><article key={scene.title} className="overflow-hidden rounded-2xl border bg-background"><Image src={scene.src} alt={scene.alt} width={1400} height={920} sizes="(min-width: 768px) 33vw, 100vw" className="aspect-[16/10] w-full object-cover" /><div className="p-5"><h3 className="font-bold">{scene.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{scene.text}</p></div></article>)}</div></div></section>

    <section id="service" className="border-y bg-card"><div className="mx-auto max-w-7xl px-4 py-16 md:px-6"><div className="text-center"><p className="text-sm font-bold text-primary">服务保障</p><h2 className="mt-3 text-3xl font-bold">从选机到使用，全程有人负责</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck,'配置清晰','按用途推荐配置，合同登记设备明细'],[Truck,'本地交付','批量设备可沟通配送与安装'],[Headphones,'售后响应','租期内设备问题及时协助处理'],[Clock3,'租期灵活','适合临时项目和阶段性用机需求']].map(([Icon,title,text]) => { const ServiceIcon=Icon as typeof BadgeCheck; return <article key={title as string} className="rounded-2xl border bg-background p-5"><ServiceIcon className="size-7 text-primary" /><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></article> })}</div></div></section>

    <section id="customer" className="mx-auto grid max-w-7xl gap-8 px-4 py-16 md:px-6 lg:grid-cols-[1fr_auto] lg:items-center lg:py-24"><div><span className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck className="size-6" /></span><h2 className="mt-5 text-balance text-3xl font-bold">已签约客户可随时查看租赁信息</h2><p className="mt-4 max-w-2xl leading-relaxed text-muted-foreground">进入客户服务中心，查看名下设备、合同期限、费用情况与服务进度。</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/customer-login" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground"><QrCode className="size-5" />进入客户服务中心</Link><a href="tel:05972685521" className="flex h-11 items-center justify-center gap-2 rounded-xl border px-5 font-semibold"><Phone className="size-5" />查询遇到问题</a></div></div><div className="mx-auto rounded-2xl border bg-card p-4 text-center shadow-lg"><Image src={qrCode} width={180} height={180} unoptimized alt="扫码进入速维客户服务中心" className="size-44" /><p className="mt-2 text-sm font-semibold">扫码进入客户服务中心</p><p className="mt-1 text-xs text-muted-foreground">www.tuzhuzu.cn/customer-login</p></div></section>

    <footer className="border-t bg-card"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm text-muted-foreground md:flex-row md:items-center md:justify-between md:px-6"><div><p className="font-semibold text-foreground">速维电脑租赁</p><p className="mt-1">租赁配置与价格以最终确认方案及合同为准</p></div><div className="flex flex-wrap gap-5"><a href="tel:05972685521">咨询电话：0597-2685521</a><Link href="/customer-login">客户服务中心</Link><Link href="/sign-in">员工登录</Link></div></div></footer>
  </main>
}
