'use client'

import Link from 'next/link'
import { ArrowRight, BadgeCheck, Check, Clock3, Cpu, Headphones, Monitor, Phone, QrCode, ShieldCheck, Truck } from 'lucide-react'

type Package = { id: number; name: string; subtitle: string; monthlyPrice: number; cpuSpec: string; memorySpec: string; storageSpec: string; graphicsSpec: string; displaySpec: string; audience: string; badge: string }

export function MarketingHome({ packages, qrCode }: { packages: Package[]; qrCode: string }) {
  return <main className="min-h-svh bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-6"><Link href="/" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Monitor className="size-5" /></span><div><p className="font-bold leading-none">速维电脑租赁</p><p className="mt-1 text-xs text-muted-foreground">企业用机 · 灵活租用</p></div></Link><nav aria-label="官网导航" className="hidden items-center gap-6 text-sm font-medium md:flex"><a href="#packages">租赁套餐</a><a href="#service">服务保障</a><a href="#customer">客户查询</a></nav><div className="flex items-center gap-2"><a href="tel:05972685521" className="hidden h-9 items-center gap-2 rounded-lg border px-3 text-sm font-semibold sm:flex"><Phone className="size-4" />0597-2685521</a><Link href="/dashboard" className="h-9 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">管理后台</Link></div></div></header>

    <section className="border-b bg-card"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 md:px-6 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div className="flex flex-col items-start justify-center"><span className="rounded-full border bg-background px-3 py-1 text-sm font-medium text-primary">龙岩本地电脑租赁服务</span><h1 className="mt-6 max-w-3xl text-balance text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">电脑不用买，<br /><span className="text-primary">按月租更省心</span></h1><p className="mt-6 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">办公扩容、临时项目、门店开业、设计剪辑和电竞活动，按需求配置设备。免去一次性采购压力，交付、维护、换机一站解决。</p><div className="mt-8 flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><a href="tel:05972685521" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 font-semibold text-primary-foreground"><Phone className="size-5" />电话咨询租机</a><Link href="/customer-login" className="flex h-12 items-center justify-center gap-2 rounded-xl border bg-background px-6 font-semibold">查看我的租赁<ArrowRight className="size-5" /></Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground">{['价格透明','按月灵活','本地服务'].map((text) => <span key={text} className="flex items-center gap-2"><Check className="size-4 text-primary" />{text}</span>)}</div></div><div className="rounded-3xl border bg-background p-5 shadow-xl sm:p-7"><div className="rounded-2xl bg-primary p-6 text-primary-foreground"><div className="flex items-start justify-between"><div><p className="text-sm opacity-75">企业办公推荐</p><h2 className="mt-2 text-2xl font-bold">商务高效电脑</h2></div><Cpu className="size-9 opacity-80" /></div><div className="mt-8 grid grid-cols-2 gap-3 text-sm"><span className="rounded-lg bg-primary-foreground/10 p-3">Core i5 / 同级</span><span className="rounded-lg bg-primary-foreground/10 p-3">16GB 内存</span><span className="rounded-lg bg-primary-foreground/10 p-3">512GB SSD</span><span className="rounded-lg bg-primary-foreground/10 p-3">显示器可选</span></div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-muted p-3"><p className="text-xl font-bold">4档</p><p className="mt-1 text-xs text-muted-foreground">公开套餐</p></div><div className="rounded-xl bg-muted p-3"><p className="text-xl font-bold">按月</p><p className="mt-1 text-xs text-muted-foreground">灵活起租</p></div><div className="rounded-xl bg-muted p-3"><p className="text-xl font-bold">本地</p><p className="mt-1 text-xs text-muted-foreground">快速响应</p></div></div></div></div></section>

    <section id="packages" className="mx-auto max-w-7xl px-4 py-16 md:px-6 lg:py-24"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">配置与月租参考</p><h2 className="mt-3 text-balance text-3xl font-bold sm:text-4xl">按场景选配置，不为闲置设备买单</h2><p className="mt-4 leading-relaxed text-muted-foreground">以下为标准套餐月租起价，实际设备品牌、成色、租期、数量和配送范围以电话确认方案为准。</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{packages.map((item) => <article key={item.id} className="flex flex-col rounded-2xl border bg-card p-5 transition-transform hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-primary">{item.badge}</p><h3 className="mt-2 text-xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.subtitle}</p></div><Monitor className="size-6 shrink-0 text-primary" /></div><p className="mt-6"><span className="text-sm text-muted-foreground">¥</span><span className="text-4xl font-bold">{item.monthlyPrice}</span><span className="text-sm text-muted-foreground"> / 月起</span></p><ul className="mt-6 flex flex-1 flex-col gap-3 text-sm">{[item.cpuSpec, item.memorySpec, item.storageSpec, item.graphicsSpec, item.displaySpec].filter(Boolean).map((spec) => <li key={spec} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{spec}</li>)}</ul><p className="mt-5 rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">适合：{item.audience}</p><a href="tel:05972685521" className="mt-4 flex h-10 items-center justify-center rounded-lg border font-semibold hover:bg-muted">咨询这套配置</a></article>)}</div></section>

    <section id="service" className="border-y bg-card"><div className="mx-auto max-w-7xl px-4 py-16 md:px-6"><div className="text-center"><p className="text-sm font-bold text-primary">服务保障</p><h2 className="mt-3 text-3xl font-bold">从选机到使用，全程有人负责</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck,'配置清晰','按用途推荐配置，合同登记设备明细'],[Truck,'本地交付','批量设备可沟通配送与安装'],[Headphones,'售后响应','租期内设备问题及时协助处理'],[Clock3,'租期灵活','适合临时项目和阶段性用机需求']].map(([Icon,title,text]) => { const ServiceIcon=Icon as typeof BadgeCheck; return <article key={title as string} className="rounded-2xl border bg-background p-5"><ServiceIcon className="size-7 text-primary" /><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></article> })}</div></div></section>

    <section id="customer" className="mx-auto grid max-w-7xl gap-8 px-4 py-16 md:px-6 lg:grid-cols-[1fr_auto] lg:items-center lg:py-24"><div><span className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck className="size-6" /></span><h2 className="mt-5 text-balance text-3xl font-bold">已经租了设备？扫码查看本人租赁信息</h2><p className="mt-4 max-w-2xl leading-relaxed text-muted-foreground">使用合同登记手机号接收短信验证码。系统仅展示该手机号对应的当前在租、即将到期或逾期设备，不开放后台操作，也不会公开其他客户数据。</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/customer-login" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground"><QrCode className="size-5" />手机验证码查询</Link><a href="tel:05972685521" className="flex h-11 items-center justify-center gap-2 rounded-xl border px-5 font-semibold"><Phone className="size-5" />查询遇到问题</a></div></div><div className="mx-auto rounded-2xl border bg-card p-4 text-center shadow-lg"><img src={qrCode} width={180} height={180} alt="扫码进入客户在租信息查询" className="size-44" /><p className="mt-2 text-sm font-semibold">微信扫码进入查询</p><p className="mt-1 text-xs text-muted-foreground">www.tuzhuzu.cn/customer-login</p></div></section>

    <footer className="border-t bg-card"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm text-muted-foreground md:flex-row md:items-center md:justify-between md:px-6"><div><p className="font-semibold text-foreground">速维电脑租赁</p><p className="mt-1">租赁配置与价格以最终确认方案及合同为准</p></div><div className="flex flex-wrap gap-5"><a href="tel:05972685521">咨询电话：0597-2685521</a><Link href="/customer-login">客户查询</Link><Link href="/sign-in">员工登录</Link></div></div></footer>
  </main>
}
