'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { MonitorCog, Plus, Save, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { deleteWebsitePackage, saveWebsitePackage } from '@/app/actions/business'

type Package = { id:number; name:string; subtitle:string; monthlyPrice:number; cpuSpec:string; memorySpec:string; storageSpec:string; graphicsSpec:string; displaySpec:string; audience:string; badge:string; active:boolean; sortOrder:number }
const empty: Omit<Package,'id'> = { name:'', subtitle:'', monthlyPrice:99, cpuSpec:'', memorySpec:'', storageSpec:'', graphicsSpec:'', displaySpec:'', audience:'', badge:'', active:true, sortOrder:50 }

export function WebsitePackageManagement({ packages }: { packages: Package[] }) {
  const router=useRouter(); const [editing,setEditing]=useState<Package|Omit<Package,'id'>|null>(null); const [pending,setPending]=useState(false)
  const update=(key:keyof Omit<Package,'id'>,value:string|number|boolean)=>setEditing((current)=>current?{...current,[key]:value}:current)
  const save=async()=>{if(!editing)return;setPending(true);try{await saveWebsitePackage(editing);toast.success('官网套餐已保存');setEditing(null);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:'保存失败')}finally{setPending(false)}}
  const remove=async(id:number)=>{if(!window.confirm('确认删除该官网套餐吗？'))return;try{await deleteWebsitePackage(id);toast.success('套餐已删除');router.refresh()}catch(error){toast.error(error instanceof Error?error.message:'删除失败')}}
  return <div className="mx-auto flex max-w-6xl flex-col gap-6 p-4 md:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">官网内容</p><h1 className="mt-1 text-2xl font-bold">租赁套餐管理</h1><p className="mt-2 text-sm text-muted-foreground">仅超级管理员可维护。这里的价格是官网公开月租参考价，不会读取或修改客户合同价格。</p></div><button onClick={()=>setEditing({...empty})} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="size-4" />新增套餐</button></header>
  {editing?<section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><MonitorCog className="size-5 text-primary" /><h2 className="font-semibold">{('id' in editing)?'编辑套餐':'新增套餐'}</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{([['name','套餐名称'],['subtitle','简短说明'],['badge','标签'],['cpuSpec','处理器'],['memorySpec','内存'],['storageSpec','存储'],['graphicsSpec','显卡'],['displaySpec','显示器'],['audience','适用场景']] as const).map(([key,label])=><label key={key} className="flex flex-col gap-2 text-sm font-medium">{label}<input value={editing[key]} onChange={(event)=>update(key,event.target.value)} className="h-10 rounded-lg border bg-background px-3" required={key==='name'} /></label>)}<label className="flex flex-col gap-2 text-sm font-medium">月租起价（元）<input type="number" min="0" value={editing.monthlyPrice} onChange={(event)=>update('monthlyPrice',Number(event.target.value))} className="h-10 rounded-lg border bg-background px-3" /></label><label className="flex flex-col gap-2 text-sm font-medium">排序<input type="number" min="0" value={editing.sortOrder} onChange={(event)=>update('sortOrder',Number(event.target.value))} className="h-10 rounded-lg border bg-background px-3" /></label><label className="flex items-center gap-2 self-end rounded-lg border p-3 text-sm font-medium"><input type="checkbox" checked={editing.active} onChange={(event)=>update('active',event.target.checked)} />官网上架展示</label></div><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setEditing(null)} className="h-10 rounded-lg border px-4 text-sm font-medium">取消</button><button disabled={pending} onClick={save} className="flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50"><Save className="size-4" />保存套餐</button></div></section>:null}
  <section className="grid gap-4 md:grid-cols-2">{packages.length===0?<div className="md:col-span-2 flex flex-col items-center gap-4 rounded-2xl border border-dashed bg-card p-10 text-center"><span className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><MonitorCog className="size-6" /></span><div><h2 className="font-semibold">还没有官网租赁套餐</h2><p className="mt-1 text-sm text-muted-foreground">新增套餐后，客户即可在官网查看公开配置与月租参考价。</p></div><button onClick={()=>setEditing({...empty})} className="flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="size-4" />新增第一个套餐</button></div>:packages.map((item)=><article key={item.id} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold">{item.name}</h2><span className={`rounded-full px-2 py-1 text-xs ${item.active?'bg-primary/10 text-primary':'bg-muted text-muted-foreground'}`}>{item.active?'已上架':'已下架'}</span></div><p className="mt-1 text-sm text-muted-foreground">{item.subtitle}</p></div><p className="shrink-0 font-bold text-primary">¥{item.monthlyPrice}/月起</p></div><p className="mt-4 text-sm leading-6">{[item.cpuSpec,item.memorySpec,item.storageSpec,item.graphicsSpec,item.displaySpec].filter(Boolean).join(' · ')}</p><p className="mt-2 text-xs text-muted-foreground">适合：{item.audience || '未填写'} · 排序 {item.sortOrder}</p><div className="mt-4 flex justify-end gap-2"><button onClick={()=>remove(item.id)} aria-label={`删除${item.name}`} className="rounded-lg border p-2 text-destructive"><Trash2 className="size-4" /></button><button onClick={()=>setEditing(item)} className="h-9 rounded-lg border px-3 text-sm font-medium">编辑</button></div></article>)}</section></div>
}
