import type { Metadata } from 'next'
import { ArrowLeft, CalendarDays, CircleUserRound, LogOut, Monitor, Phone, ReceiptText, ShieldCheck, Store } from 'lucide-react'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import { formatDeviceConfig } from '@/lib/device-config'
import { getCustomerActiveRentals } from '@/lib/customer-phone-auth'

export const metadata: Metadata = { title: '我的在租信息 | 速维租赁', robots: { index: false, follow: false } }
const money = (value: string) => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(Number(value))

export default async function CustomerPage() {
  const data = await getCustomerActiveRentals()
  if (!data) redirect('/customer-login')
  const maskedPhone = `${data.phone.slice(0, 3)}****${data.phone.slice(-4)}`
  return <main className="min-h-svh bg-background pb-10">
    <nav className="mx-auto flex max-w-4xl items-center justify-between px-4 py-3"><Link href="/" className="flex items-center gap-2 text-sm font-medium text-muted-foreground"><ArrowLeft className="size-4" />返回官网</Link><form action="/api/customer-auth/logout" method="post"><button aria-label="退出客户登录" className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-medium"><LogOut className="size-4" />退出</button></form></nav>
    <header className="bg-primary px-4 pb-9 pt-7 text-primary-foreground"><div className="mx-auto flex max-w-4xl flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-sm opacity-80"><Store className="size-4" />{data.shopName}</p><h1 className="mt-2 text-balance text-3xl font-bold">{data.customerName}，您好</h1><p className="mt-2 text-sm opacity-80">已验证手机号 {maskedPhone} · 仅展示当前在租信息</p></div><div className="rounded-xl bg-primary-foreground/10 px-4 py-3 text-sm"><p className="opacity-75">当前在租合同</p><p className="mt-1 text-2xl font-bold">{data.contracts.length} 份</p></div></div></header>
    <div className="mx-auto -mt-4 flex max-w-4xl flex-col gap-5 px-4">
      <section className="grid gap-4 sm:grid-cols-2"><article className="flex items-start gap-3 rounded-2xl border bg-card p-4 shadow-sm"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><h2 className="font-semibold">只读安全门户</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">您只能查看本人在租、即将到期或逾期的合同，无法修改任何业务资料。</p></div></article><article className="flex items-start gap-3 rounded-2xl border bg-card p-4 shadow-sm"><CircleUserRound className="mt-0.5 size-5 shrink-0 text-primary" /><div><h2 className="font-semibold">客户负责人</h2>{data.assignee ? <><p className="mt-1 text-sm text-muted-foreground">{data.assignee.name}</p>{data.assignee.phone ? <a className="mt-1 inline-flex items-center gap-2 text-sm font-medium text-primary" href={`tel:${data.assignee.phone}`}><Phone className="size-4" />{data.assignee.phone}</a> : <p className="mt-1 text-sm text-muted-foreground">联系电话暂未设置</p>}</> : <p className="mt-1 text-sm text-muted-foreground">店铺暂未分配专属负责人</p>}</div></article></section>
      {data.contracts.length ? data.contracts.map((contract) => { const items = data.items.filter((item) => item.rentalId === contract.id); return <article key={contract.id} className="overflow-hidden rounded-2xl border bg-card shadow-sm"><header className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">合同 {contract.contractNo}</h2><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">{contract.status}</span></div><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="size-4" />{contract.startDate} 至 {contract.endDate}</p></div><div className="text-left sm:text-right"><p className="text-xs text-muted-foreground">付款状态</p><p className="mt-1 font-semibold">{contract.paymentStatus}</p></div></header><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4"><Summary label="月租金" value={money(contract.monthlyRent)} /><Summary label="合同总额" value={money(contract.totalRent)} /><Summary label="已支付" value={money(contract.paidAmount)} /><Summary label="押金" value={money(contract.deposit)} /></div><section className="flex flex-col gap-3 p-5"><h3 className="flex items-center gap-2 font-semibold"><Monitor className="size-4 text-primary" />设备明细</h3>{items.length ? items.map((item) => <div key={item.id} className="rounded-xl border bg-background p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.deviceName}</p><p className="mt-1 text-sm text-muted-foreground">{item.deviceType}{item.deviceCode ? ` · 设备编号 ${item.deviceCode}` : ''}</p></div><span className="rounded-lg bg-muted px-2 py-1 text-sm">× {item.quantity}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{formatDeviceConfig(item.deviceConfig ?? '') || '配置详情请联系负责人'}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>租期：{item.startDate || contract.startDate} 至 {item.endDate || contract.endDate}</span><span>月租：{money(item.monthlyRent)}</span><span>合计：{money(item.totalRent)}</span></div></div>) : <div className="rounded-xl bg-muted p-4 text-sm text-muted-foreground">{contract.deviceName} · {contract.deviceType} · 共 {contract.quantity} 台</div>}</section>{contract.notes ? <footer className="flex items-start gap-2 border-t bg-muted/50 px-5 py-4 text-sm text-muted-foreground"><ReceiptText className="mt-0.5 size-4 shrink-0" /><span>{contract.notes}</span></footer> : null}</article> }) : <section className="rounded-2xl border border-dashed bg-card p-10 text-center"><Monitor className="mx-auto size-10 text-muted-foreground" /><h2 className="mt-4 font-semibold">暂无当前在租信息</h2><p className="mt-2 text-sm text-muted-foreground">已退租或已结束的合同不会在这里显示。</p></section>}
    </div>
  </main>
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
